version: "3"
services:
  freeswitch:
    image: 'xsdhy/freeswitch:1.10.12'
    container_name: freeswitch
    network_mode: host
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./conf:/usr/local/freeswitch/conf"
      - "./sounds/test:/usr/local/freeswitch/sounds/test"
